### ISSUE TITLE
PHPSpec uses the deprecated autoload path

### ISSUE THREAD

**Issue by paulschwarz** [zombor/Auto-Modeler-Demo#4]
https://github.com/zombor/Auto-Modeler-Demo/blob/master/composer.json#L5 "cordoval" seems to be out of date. 
The issue is a breaking change as described here:
https://groups.google.com/forum/#!msg/composer-dev/fWIs3KocwoA/nU3aLko9LhQJ

There must be a newer version to point composer to?

**Comment by zeebinz** [comment]
This works:

```
{
    "require": {
        "phpspec/phpspec": "dev-develop"
    },

    "repositories": [
        {
            "type": "vcs",
            "url": "git://github.com/phpspec/phpspec.git"
        },
        {
            "type": "package",
            "package": {
                "name": "phpunit/text_template",
                "version": "1.1.1",
                "dist": {
                    "url": "http://pear.phpunit.de/get/Text_Template-1.1.1.tgz",
                    "type": "pear"
                },
                "autoload": {
                    "psr-0": { "Text": "" }
                }
            }
        }
    ]
}
```

You can also specify the actual commit in the require statement now, like dev-develop#abcdef.

**Comment by zombor** [comment]
The reason I like the cordoval repo is that it includes stuff like mockery as well.

**Comment by zeebinz** [comment]
So does this one - Mockery will be automatically installed.

**Comment by paulschwarz** [comment]
Thanks for the info zeebinz, I'll check it out. @zombor, in the mean time the good news is that cordoval accepted my pull request so we're good to continue now without having to manually edit the file.

https://github.com/cordoval/phpspec/commit/4dd4e433088dcb669f335a78e4b687f2eea08759
